# Generated by Django 2.2.7 on 2019-11-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kregielnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('idKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='listaTorow',
            fields=[
                ('nrToru', models.AutoField(primary_key=True, serialize=False)),
                ('stan', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pensje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('idPracownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('stanowisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='wynajemToru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czasWynajecia', models.CharField(max_length=40)),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kregielnia.Klienci')),
                ('nrToru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kregielnia.listaTorow')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='pensje',
            name='Pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kregielnia.Pracownicy'),
        ),
    ]
